### ISSUE TITLE
Bug: code undefined undefined

### ISSUE THREAD

**Issue by fatinghenji** [koishijs/koishi-plugin-booru#103]
### Describe the bug

```
2023-10-29 21:59:27 [W] booru source danbooru request failed with code undefined undefined
```

### Steps to reproduce

调用booru

### Expected behavior

正常调用

### Relevant log output

```shell
2023-10-29 21:59:25 [W] app Error: property booru is not registered, declare it as `inject` to suppress this warning
                            at checkInject (/data/data/com.termux/files/home/koishi-app/node_modules/cordis/lib/index.cjs:776:36)
                            at Object.get (/data/data/com.termux/files/home/koishi-app/node_modules/cordis/lib/index.cjs:793:9)
                            at _Command.<anonymous> (/data/data/com.termux/files/home/koishi-app/node_modules/koishi-plugin-booru/lib/index.js:127:32)
                            at Array.<anonymous> (/data/data/com.termux/files/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1331:27)
                            at argv.next (/data/data/com.termux/files/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1343:60)
                            at _Command.execute (/data/data/com.termux/files/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1346:33)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async /data/data/com.termux/files/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2175:22
                            at async _Session.withScope (/data/data/com.termux/files/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2077:22)
                            at async next (/data/data/com.termux/files/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1053:16)
2023-10-29 21:59:27 [W] booru source danbooru request failed with code undefined undefined
```

### Launcher

Koishi CLI (koishi start)

### Sources

Danbooru

### Versions

- OS: andorid12
- Adapter: 无，在沙盒中测试
- Node version: v18.16.1
- Koishi version: 4.15.3

**Comment by MaikoTan** [comment]
Is it only happen on `danbooru` or every source?

它只发生在 `danbooru` 还是所有的源头？

**Comment by fatinghenji** [comment]
每个源都有这个问题，参看：[正确使用的姿势是什么？](https://github.com/koishijs/koishi-plugin-booru/discussions/71#discussioncomment-5807796)

**Comment by Lipraty** [comment]
> 2023-10-29 21:59:25 [W] app Error: property booru is not registered, declare it as `inject` to suppress this warning

This **warning** can be ignore that occurs in Koishi versions `4.15.2` and above.

这个警告是可以忽略的在 Koishi 4.15.2 及以上。

And the `code undefined undefined` indicates that your connection was severed before it could reach the server. Please check your network and Proxy/VPN settings. However, a check can be conducted here to ensure the readability of the logs.

而“code undefined undefined”表示连接在到达服务器之前已被切断。请检查您的网络和代理/VPN 设置。不过，可以在这里进行检查以确保日志的可读性。

**Comment by MaikoTan** [comment]
Still I cannot reproduce it.

![image](https://github.com/koishijs/koishi-plugin-booru/assets/19927330/a4703ca6-046d-4557-a770-97d240812819)

**Comment by Lipraty** [comment]
fixed.

**Comment by fatinghenji** [comment]
> fixed.

依旧存在：
```
2023-11-11 18:00:38 [W] booru source yande request failed with code undefined undefined
2023-11-11 18:00:59 [W] booru source konachan request failed with code undefined undefined
2023-11-11 18:01:21 [W] booru source pixiv request failed with code undefined undefined
2023-11-11 18:01:21 [W] booru source sankaku request failed with code undefined undefined
2023-11-11 18:01:42 [W] booru source danbooru request failed with code undefined undefined
```

**Comment by MaikoTan** [comment]
I have published version 1.1.1 which includes the bug fixes, please upgrade your plugin

**Comment by fatinghenji** [comment]
更新至1.1.1后，报错变为：
```
2023-11-11 23:36:54 [W] booru source danbooru request failed 
2023-11-11 23:37:15 [W] booru source yande request failed 
2023-11-11 23:37:36 [W] booru source konachan request failed 
```
在相同网络环境下，浏览器可以正常访问网址。

**Comment by MaikoTan** [comment]
> And the `code undefined undefined` indicates that your connection was severed before it could reach the server. Please check your network and Proxy/VPN settings. However, a check can be conducted here to ensure the readability of the logs.
> 
> 而“code undefined undefined”表示连接在到达服务器之前已被切断。请检查您的网络和代理/VPN 设置。不过，可以在这里进行检查以确保日志的可读性。

There's nothing to do about your network issues from our side.

**Comment by Lipraty** [comment]
> 更新至1.1.1后，报错变为：
> 
> ```
> 2023-11-11 23:36:54 [W] booru source danbooru request failed 
> 2023-11-11 23:37:15 [W] booru source yande request failed 
> 2023-11-11 23:37:36 [W] booru source konachan request failed 
> ```
> 
> 在相同网络环境下，浏览器可以正常访问网址。

plz edit your `koishi.yml`:

```yml
...
logger: # is root
    levels:
        booru: 3
...
```
copy the logs starting with `[D] booru`
