### ISSUE TITLE
Bug: 无法发送复数张图片

### ISSUE THREAD

**Issue by CaoMeiYouRen** [koishijs/koishi-plugin-booru#124]
### Describe the bug

可以正常发送单张图片，但在两张以上的时候会出现消息源码。
在钉钉、企业微信平台表现为发送消息源码；在onebot平台为发送错误，没有返回消息。

### Steps to reproduce

```sh
booru -c 1 # 此时会正常返回1张图片
booru -c 2 # 此时会返回消息源码
```

### Expected behavior

应当正常返回指定数量的图片

### Screenshots

![image](https://github.com/koishijs/koishi-plugin-booru/assets/40430746/6e6df09b-fecd-44fe-b0f9-fb3772554f87)
![image](https://github.com/koishijs/koishi-plugin-booru/assets/40430746/5944acc5-612a-4263-81ba-efd6e383ff64)
![image](https://github.com/koishijs/koishi-plugin-booru/assets/40430746/aff91279-67bb-4125-9be1-e907d0920830)
![image](https://github.com/koishijs/koishi-plugin-booru/assets/40430746/abd308a6-f5f9-4e40-a07d-9eb782d88813)

### Relevant log output

```shell
2023-11-29 10:45:46 [W] session Error: Error with request send_private_forward_msg, args: {"user_id":123456,"messages":[{"type":"node","data":{"name":"香风友希子","uin":"xxxxxx","content":[{"type":"text","data":{"text":"<message><image url=\"https://i.pixiv.re/img-original/img/2020/11/03/20/57/58/85441461_p0.jpg\"/></message>\n<message><image url=\"https://i.pixiv.re/img-original/img/2022/07/24/00/00/08/99945802_p0.jpg\"/></message>"}}],"time":"1701225945"}}]}, retcode: 103
                            at Internal._get (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/types.js:41:15)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Internal.<computed> [as sendPrivateForwardMsg] (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/types.js:81:26)
                            at async OneBotMessageEncoder.forward (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/bot/message.js:22:20)
                            at async OneBotMessageEncoder.visit (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/bot/message.js:217:17)
                            at async OneBotMessageEncoder.render (/koishi/node_modules/@satorijs/core/lib/index.cjs:544:7)
                            at async OneBotMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:576:5)
                            at async OneBotBot.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:338:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2192:7
                            at async Proxy.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2087:22)
```

### Launcher

Containers (Docker, Kubernates, etc)

### Sources

Lolicon

### Versions

- OS: Linux 3.10 Alpine Linux
- Adapter: dingtalk/wecom/onebot
- Node version: 20.9.0
- Koishi version: 4.15.6

### Additional context

- booru: 1.1.1
- booru-lolicon: 1.1.0
![image](https://github.com/koishijs/koishi-plugin-booru/assets/40430746/a71615a9-5fa6-426d-8566-d4db8f7b1bc4)

**Comment by Lipraty** [comment]
I cannot reproduce it. This can be caused by the inability of the adapter to handle nested message elements.

![image](https://github.com/koishijs/koishi-plugin-booru/assets/18106422/c4a0e9d3-b29e-475d-8487-3911c1b3e2f8)

**Comment by CaoMeiYouRen** [comment]
> I cannot reproduce it. This can be caused by the inability of the adapter to handle nested `<message>` elements.
> 
> ![image](https://private-user-images.githubusercontent.com/18106422/286462669-c4a0e9d3-b29e-475d-8487-3911c1b3e2f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjg0NjIsIm5iZiI6MTcwMTIyODE2MiwicGF0aCI6Ii8xODEwNjQyMi8yODY0NjI2NjktYzRhMGU5ZDMtYjI5ZS00NzVkLTg0ODctMzkxMWMxYjNlMmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAzMjI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NWVhMWJlNDRmOGUwYjNhMTIyMTdhNmE1YjdmOTk4ZmYyZjNmZjBjMWE4ZTEwZmY3MWFkNTNhZTlmYTRkOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u-dXZQ4a65FZJP-L9lMe3xFhEENXjWwd5uLUSGac3d4)

在沙盒中也是这样的
![image](https://github.com/koishijs/koishi-plugin-booru/assets/40430746/c8ec226a-7063-4f01-85c0-8c4ccc23394f)

**Comment by Lipraty** [comment]
However, the `OneBot` adapter is no longer actively being developed, `DingTalk` with `WeCom` adapter by LittleC.

> https://github.com/whitechi73/OpenShamrock/issues/64#issuecomment-1821427719
>
> 既然这个 issue 已经关闭，你可以去 [koishi-plugin-adapter-onebot](https://github.com/koishijs/koishi-plugin-adapter-onebot) 再发一个 issue。但 onebot 适配器已经不积极维护了，可以等待有缘人来研究（
>
> https://github.com/koishijs/koishi-plugin-adapter-onebot/issues/5

 cc @XxLittleCxX

**Comment by Lipraty** [comment]
> 在沙盒中也是这样的 ![image](https://private-user-images.githubusercontent.com/40430746/286466543-c8ec226a-7063-4f01-85c0-8c4ccc23394f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjg2MTUsIm5iZiI6MTcwMTI2ODMxNSwicGF0aCI6Ii80MDQzMDc0Ni8yODY0NjY1NDMtYzhlYzIyNmEtNzA2My00ZjAxLTg1YzAtOGM0Y2NjMjMzOTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE0MzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYjA4YjAxNzhmOTQ5ZGI4NDViN2MxMWZlNzU2MjA1N2E3ZjI0ZDRkZGJjNDc0YTM0ZjBjNDNlYzdkNGI2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xf3eFBgAYcyy5SaVWV-DgY3kMdTrNgQg4TvII07fQaY)

please upgrade sandbox plugin.

**Comment by CaoMeiYouRen** [comment]
> > 在沙盒中也是这样的 ![image](https://private-user-images.githubusercontent.com/40430746/286466543-c8ec226a-7063-4f01-85c0-8c4ccc23394f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjg2MTUsIm5iZiI6MTcwMTI2ODMxNSwicGF0aCI6Ii80MDQzMDc0Ni8yODY0NjY1NDMtYzhlYzIyNmEtNzA2My00ZjAxLTg1YzAtOGM0Y2NjMjMzOTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE0MzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYjA4YjAxNzhmOTQ5ZGI4NDViN2MxMWZlNzU2MjA1N2E3ZjI0ZDRkZGJjNDc0YTM0ZjBjNDNlYzdkNGI2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xf3eFBgAYcyy5SaVWV-DgY3kMdTrNgQg4TvII07fQaY)
> 
> please upgrade sandbox plugin.

HI，所有插件均已升级到最新，依旧是这样的
![image](https://github.com/koishijs/koishi-plugin-booru/assets/40430746/cfa7822b-fe58-4b58-a7fc-c07a83ab8e2e)
![image](https://github.com/koishijs/koishi-plugin-booru/assets/40430746/8fe4e3f3-3932-4451-84e1-a5480aa92842)

**Comment by Lipraty** [comment]
We have discovered that the releases packages without applying the most recent modifications and incorrectly publishes a version that is still being edited. Please wait for the latest version to be released. 

Thanks for your issue.

**Comment by Lipraty** [comment]
Maybe that's why we cannot replicate the issue, as a local development version is employed.

**Comment by Lipraty** [comment]
New version has been released, please wait for the marketplace to be updated and try again.

**Comment by CaoMeiYouRen** [comment]
> New version has been released, please wait for the marketplace to be updated and try again.

感谢，问题已解决。企业微信、钉钉、沙盒中都可以正常返回了。
