### ISSUE TITLE
Bug: 使用koishi v4.15.0 安装时出现错误

### ISSUE THREAD

**Issue by eric2788** [koishijs/koishi-plugin-booru#99]
### Describe the bug

错误日志如下
```log
config failed to resolve koishi-plugin-booru
2023-10-11 14:30:20 [W] config Error: Cannot find module 'koishi-plugin-booru'
                        Require stack:
                        - /koishi/node_modules/@koishijs/registry/lib/index.js
                        - /koishi/node_modules/@koishijs/plugin-config/lib/node/index.js
                        - /koishi/node_modules/@koishijs/loader/lib/index.js
                        - /koishi/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
                            at Function.resolve (node:internal/modules/cjs/helpers:127:19)
                            at _PackageScanner.loadPackage (/koishi/node_modules/@koishijs/registry/lib/index.js:165:29)
                            at _PackageScanner.loadDirectory (/koishi/node_modules/@koishijs/registry/lib/index.js:151:14)
                            at async Promise.all (index 0)
                            at async _PackageScanner._collect (/koishi/node_modules/@koishijs/registry/lib/index.js:138:5)
                            at async _PackageScanner.collect (/koishi/node_modules/@koishijs/registry/lib/index.js:143:5)
                            at async _PackageProvider.collect (/koishi/node_modules/@koishijs/plugin-config/lib/node/index.js:71:5)
                            at async _PackageProvider.get (/koishi/node_modules/@koishijs/plugin-config/lib/shared/index.js:67:22)
                            at async _PackageProvider.refresh (/koishi/node_modules/@koishijs/console/lib/index.js:71:14)
```                            

### Steps to reproduce

到插件市场安装本插件

### Expected behavior

顺利启动插件

### Screenshots

![image](https://github.com/koishijs/koishi-plugin-booru/assets/6276840/be9e0f14-72dc-4993-bbbf-e67a092a66a9)

### Relevant log output

```shell
2023-10-11 14:30:20 [W] config failed to resolve koishi-plugin-booru
2023-10-11 14:30:20 [W] config Error: Cannot find module 'koishi-plugin-booru'
                        Require stack:
                        - /koishi/node_modules/@koishijs/registry/lib/index.js
                        - /koishi/node_modules/@koishijs/plugin-config/lib/node/index.js
                        - /koishi/node_modules/@koishijs/loader/lib/index.js
                        - /koishi/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
                            at Function.resolve (node:internal/modules/cjs/helpers:127:19)
                            at _PackageScanner.loadPackage (/koishi/node_modules/@koishijs/registry/lib/index.js:165:29)
                            at _PackageScanner.loadDirectory (/koishi/node_modules/@koishijs/registry/lib/index.js:151:14)
                            at async Promise.all (index 0)
                            at async _PackageScanner._collect (/koishi/node_modules/@koishijs/registry/lib/index.js:138:5)
                            at async _PackageScanner.collect (/koishi/node_modules/@koishijs/registry/lib/index.js:143:5)
                            at async _PackageProvider.collect (/koishi/node_modules/@koishijs/plugin-config/lib/node/index.js:71:5)
                            at async _PackageProvider.get (/koishi/node_modules/@koishijs/plugin-config/lib/shared/index.js:67:22)
                            at async _PackageProvider.refresh (/koishi/node_modules/@koishijs/console/lib/index.js:71:14)
```

### Launcher

Containers (Docker, Kubernates, etc)

### Sources

Pixiv

### Versions

- OS: 
- Adapter: red
- Node version: 
- Koishi version: 4.15.0

**Comment by eric2788** [comment]
卸載插件後重載 依然出現這個錯誤，且插件設置會顯示有錯誤無法顯示配置頁面
卸載後沒有這個錯誤

**Comment by eric2788** [comment]
umm 我明天再試試安裝一次

**Comment by eric2788** [comment]
今早嘗試安裝發現沒有了昨晚的問題，很玄

**Comment by MaikoTan** [comment]
Good.
I think you had a failed installation at the last time, glad you found it working now.
